export const CONFIGURATION_UPDATE = "CONFIGURATION_UPDATE";

export const SPRINT_UPDATE = "SPRINT_UPDATE";
export const SPRINT_STARTED = "SPRINT_STARTED";
export const SPRINT_CANCELLED = "SPRINT_CANCELLED";
export const SPRINT_ENDED = "SPRINT_ENDED";

export const MESSAGE_ADD = "MESSAGE_ADD";
export const MESSAGE_REMOVE = "MESSAGE_REMOVE";

export const PARTICIPANT_ADD = "PARTICIPANT_ADD";
export const PARTICIPANT_REMOVE = "PARTICIPANT_REMOVE";
export const PARTICIPANTS_RESET = "PARTICIPANTS_RESET";
export const PARTICIPANTS_ADD_LIVES = "PARTICIPANTS_ADD_LIVES";
export const PARTICIPANTS_REMOVE_LIVE = "PARTICIPANTS_REMOVE_LIVE";

export const RANKING_UPDATE = "RANKING_UPDATE";
export const RANKING_PARTICIPANT_ADD = "RANKING_PARTICIPANT_ADD";
export const RANKING_RESET = "RANKING_RESET";
