export const CONFIGURATION_UPDATE = "CONFIGURATION_UPDATE";

export const SPRINT_UPDATE = "SPRINT_UPDATE";
export const SPRINT_STARTED = "SPRINT_STARTED";
export const SPRINT_CANCELLED = "SPRINT_CANCELLED";
export const SPRINT_ENDED = "SPRINT_ENDED";

export const PARTICIPANT_ADD = "PARTICIPANT_ADD";
export const PARTICIPANT_REMOVE = "PARTICIPANT_REMOVE";
export const PARTICIPANTS_RESET = "PARTICIPANTS_RESET";
export const PARTICIPANTS_ADD_LIVES = "PARTICIPANTS_ADD_LIVES";
export const PARTICIPANTS_REMOVE_LIVE = "PARTICIPANTS_REMOVE_LIVE";

export const GOAL_UPDATE = "GOAL_UPDATE";
export const GOAL_REPLACE = "GOAL_REPLACE";

export const RANKING_UPDATE = "RANKING_UPDATE";
export const RANKING_PARTICIPANT_ADD = "RANKING_PARTICIPANT_ADD";
export const RANKING_PARTICIPANT_UPDATE = "RANKING_PARTICIPANT_UPDATE";
export const RANKING_RESET = "RANKING_RESET";

export const VIP_UPDATE = "VIP_UPDATE";
export const VIP_ADD_PERSON = "VIP_ADD_PERSON";
export const VIP_REMOVE_PERSON = "VIP_REMOVE_PERSON";
